# Generated by Django 5.1.7 on 2025-04-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='apt', max_length=60),
            preserve_default=False,
        ),
    ]
