# Generated by Django 5.1.7 on 2025-04-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('email', models.EmailField(max_length=70)),
                ('city', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
